import { COMPONENT_NAMES } from './COMPONENT_NAMES';

export const COMPONENTS_LIST = [
  {
    title: 'Controls',
    isExpanded: true,
    components: [
      COMPONENT_NAMES.AUTO_COMPLETE,
      COMPONENT_NAMES.CHECKBOX,
      COMPONENT_NAMES.BUTTON,
      COMPONENT_NAMES.COLOR_PICKER,
      COMPONENT_NAMES.COMBO_BOX,
      COMPONENT_NAMES.FILE_UPLOAD,
      COMPONENT_NAMES.ICON_BUTTON,
      COMPONENT_NAMES.ICONS,
      COMPONENT_NAMES.INPUTS,
      COMPONENT_NAMES.MODALS,
      COMPONENT_NAMES.POPOVER,
      COMPONENT_NAMES.PROGRESS_BAR,
      COMPONENT_NAMES.RADIO_GROUP,
      COMPONENT_NAMES.RATINGS,
      COMPONENT_NAMES.SEGMENTED_BUTTONS,
      COMPONENT_NAMES.SELECT,
      COMPONENT_NAMES.SLIDER,
      COMPONENT_NAMES.SPINNER,
      COMPONENT_NAMES.TEXT_AREA,
      COMPONENT_NAMES.TOAST,
      COMPONENT_NAMES.TOOL_TIPS,
    ],
  },
  {
    title: 'Containers',
    components: [
      COMPONENT_NAMES.ACCORDION,
      COMPONENT_NAMES.CARD,
      COMPONENT_NAMES.HBOX,
      COMPONENT_NAMES.VBOX,
      COMPONENT_NAMES.PANEL,
      COMPONENT_NAMES.DATE_PICKER,
      COMPONENT_NAMES.DROPDOWN,
    ],
  },
  {
    title: 'Navigators',
    components: [],
  },
  {
    title: 'Datatables',
    components: [],
  },
  {
    title: 'Templates',
    components: [],
  },
];
