import { DESIGN_BRAND_NAMES } from './DESIGN_BRAND_NAMES';

export const DESIGN_BRAND_LIST = [
  {
    title: 'Brand',
    isExpanded: true,
    components: [
      DESIGN_BRAND_NAMES.PHILOSOPHY,
      DESIGN_BRAND_NAMES.COLOR,
      DESIGN_BRAND_NAMES.ILLUSTRATION,
      DESIGN_BRAND_NAMES.IMAGES,
      DESIGN_BRAND_NAMES.PHOTOGRAPHY,
      DESIGN_BRAND_NAMES.ICONOGRAPHY,
      DESIGN_BRAND_NAMES.TYPOGRAPHY,
      DESIGN_BRAND_NAMES.DESIGN_KIT,
    ],
  }
];
